name: release

on:
  push:
    branches:
      - gh-pages
    paths:
        - 'charts/**'
  workflow_dispatch: { }

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
            skip_existing: true
            packages_with_index: true
        env:
          CR_TOKEN: "${{ secrets.GIT_PUB_AUTH_TOKEN }}"